# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Mongli' do
  use_frameworks!

  # Architecture
  pod 'ReactorKit'

  # Networking
  pod 'Alamofire'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Kingfisher'
  pod 'ObjectMapper', '~> 3.4'

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'

  # UI
  pod 'SnapKit'
  pod 'Hero'
  pod 'FSCalendar'
  pod 'NVActivityIndicatorView'

  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  # etc
  pod 'Then'

  target 'MongliTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MongliUITests' do
    # Pods for testing
  end

end
